# Change these first
owner: redir-org # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: redir
    url: https://redir.us.kg
  - name: accounts.redir
    url: https://accounts.redir.us.kg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.redir.us.kg
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/redir-org/status/master/assets/redir.png
  name: redir
  introTitle: "**redir** is a link shortner."
  introMessage: See the current and status history.
  theme: dark
  navbar:
    - title: Status
      href: /

assignees:
  - lrxrn

skipDeleteIssues: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
